# src/agent/state.py
"""Agent state definitions for SocrAItes.

This module defines the structured state that is passed between LangGraph nodes.
It uses ``TypedDict`` for static type checking while remaining JSON‑serializable.
"""

from __future__ import annotations

from typing import TypedDict, List, Dict, Any

class AgentState(TypedDict, total=False):
    """TypedDict representing the mutable state of a conversation turn.

    - ``messages``: List of message dicts exchanged so far.
    - ``socratic_depth``: Current depth mode (0=Light, 1=Standard, 2=Deep).
    - ``frustration_level``: Counter of detected frustration signals.
    - ``retrieved_docs``: List of document chunks retrieved from the vector store.
    - ``next_step``: Signal for routing (e.g., 'planner', 'direct_response', 'end').
    - ``plan``: The execution plan generated by the Planner.
    - ``draft_answer``: The response generated by the Supervisor.
    - ``evaluation``: Results from the Evaluator node.
    - ``session_id``: UUID for the current database session.
    """

    messages: List[Dict[str, Any]]
    socratic_depth: int
    frustration_level: int
    retrieved_docs: List[Any]
    next_step: str
    plan: str
    draft_answer: str
    evaluation: Dict[str, Any]
    session_id: str

# Default initial state
DEFAULT_STATE: AgentState = {
    "messages": [],
    "socratic_depth": 1,  # Default to Standard
    "frustration_level": 0,
    "retrieved_docs": [],
    "next_step": "",
    "plan": "",
    "draft_answer": "",
    "evaluation": {},
    "session_id": "",
}
